### ISSUE TITLE
Using SpaGCN without image

### ISSUE THREAD

**Issue by Yao-14** [jianhuupenn/SpaGCN#11]
Hallo, 

I am very interested in SpaGCN, but I don’t have a stained image. Can I run SpaGCN only with  gene expression data and spatial location data,  and get a good result?

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. Yes, SpaGCN can be applied to ST data without histology images. The only difference is the way of calculating the adjacent matrix. For more details and guidance, please refer to the tutorial 
https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md
Section 4. Integrate gene expression and histology into a Graph
```
#If histlogy image is not available, SpaGCN can calculate the adjacent matrix using the function below
adj=calculate_adj_matrix(x=x_pixel,y=y_pixel, histology=False)
```
Jian

**Comment by Yao-14** [comment]
Well, thank you very much for your reply, which is very useful to me. 
I have a new confusion. I found that SpaGCN integrates the process of performing PCA, computing neighbor graphs, and clustering, but I now have multiple batches of data that I want to integrate, and then cluster. 
At the same time, the suggestion given by Scanpy is to perform PCA  first, then Use harmony to integrate different batches, and then compute the neighbor graph. How can I implement this process in SpaGCN ?

**Comment by jianhuupenn** [comment]
The goal of SpaGCN is to identify the spatial domain in a single section and do not any steps for batch effect removal. If you are interested in analyzing multiple sections from different tissue samples, you can refer to my suggestions in:
https://github.com/jianhuupenn/SpaGCN/issues/6
If the tissue sections are from the same tissue and are spatially adjacent to each other, you can refer to my tutorial part 
8. Multiple tissue sections analysis
https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md#8-multiple-tissue-sections-analysis
