### ISSUE TITLE
Have a question about q value in your code

### ISSUE THREAD

**Issue by tlz4320** [jianhuupenn/SpaGCN#12]
Excuse me to bother you about this.
I'm reading your code and your paper, but I don't understand in your paper, "q" is calculated bu this formula.
![image](https://user-images.githubusercontent.com/24791715/142760735-9e7ab2ea-1b18-4846-a95b-7e94587aec09.png)

And in your code of models.py, "q" is calculated by
![image](https://user-images.githubusercontent.com/24791715/142760783-8f8deb8f-255f-4d9e-b2ba-09a3d07bd9b3.png)
Is this formula from your code is the implement of formula of your paper? and is this two formulas are same.

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. I think that is a typo that we didn’t catch. The definition of qij should be:
<img width="250" alt="Screen Shot 2021-11-21 at 11 59 05 AM" src="https://user-images.githubusercontent.com/26659799/142771814-cebab2ef-634d-49e7-a153-c497a80cc270.png">
Thanks for raising this up and we will contact the journal to make corrections.
