### ISSUE TITLE
Annotate based on SpaGCN

### ISSUE THREAD

**Issue by Yao-14** [jianhuupenn/SpaGCN#13]
Hello, during my process of identifying SVGs and meta genes through SpaGCN, I encountered the following problems:

1. In the process of identifying SVGs, some domains cannot identify a gene. How can I adjust the parameters more appropriately?
        Cluster 2 has neighbors:
        Dmain  6 :  149
        Dmain  1 :  140
        Dmain  5 :  136
        [6, 1, 5]
        SVGs for domain  2 : []

2. In the process of identifying meta genes, is the start gene we input the gene with the highest in_group_fraction value obtained in the process of identifying SVGs?

3. In the process of identifying meta genes, sometimes the meta genes obtained are in the following situations, what should I do?
        SVGs for domain  5 : ['Mlc2']
        Meta gene is:  Mlc2+CG15282-Mlc2

4. If I want to annotate domains with genes obtained by SpaGCN, should I choose SVGs or meta genes?

**Comment by jianhuupenn** [comment]
1. You can try:
 ```
min_in_group_fraction=0.8 #(can be changed to 0.5 or lower)
min_in_out_group_ratio=1  #(can be changed to 0.5 or lower)
min_fold_change=1.5 #(can be changed to 1.2 or lower)
```
2. It depends on what pattern you want. Usually, you can use the gene with the highest "in_group_fraction" or highest "fold change". 
3. You can try a different start gene or plot Mlc2+CG15282 to see if it is a good meta marker. 
4. I would suggest you plot the SVG first. If SVGs already have clear patterns, then no need for meta gene.
