### ISSUE TITLE
Link to download the ground truth

### ISSUE THREAD

**Issue by JunMa11** [jianhuupenn/SpaGCN#16]
Hi @jianhuupenn , 

Thanks for your quick reply.

I'm sorry to open a new issue because I cannot re-open the original issue.

I do not find the ground truth on http://research.libd.org/spatialLIBD/
![1640029955](https://user-images.githubusercontent.com/19947331/146824584-95d7a29c-6684-4e47-b913-74d92272782f.png)

Could you please share the link to the ground truth?

**Comment by jianhuupenn** [comment]
Sorry, I don't remember the exact webpage. I think I download them from the LIBD's author's GitHub repository.

**Comment by JunMa11** [comment]
Hi @jianhuupenn ,

Thanks for your reply. 

I spent lots of effort but still do not find the ground truth. Would it be possible for you to send them to me via email? (junma@njust.edu.cn) 

Kindest regards,
Jun

**Comment by jianhuupenn** [comment]
I don't have access to the data currently. Can you double-check the LIBD package? I think I got the true label from it.

**Comment by JunMa11** [comment]
Thank you.
The download R code does not work on my laptop.
 I will try to ask the data organizers.
