### ISSUE TITLE
n_clusters is not used in louvain initialization

### ISSUE THREAD

**Issue by EdwardZhao1991** [jianhuupenn/SpaGCN#17]
The initialization method has a significant impact on the final results, e.g., if change the `init="louvain" to init="kmeans" in the tutorial https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md.

I also dig into the code, it seems that the variable `n_clusters` is only used in kmeans. Why it is not used in louvain? How to specify the number of clusters in louvain? because sometimes louvain gives wrong estimations on the number of clusters even if the cluster number has been specified in searching `res`. 

https://github.com/jianhuupenn/SpaGCN/blob/c2ba31da43b7b5e2caf576c6ab666ce91e26ece8/SpaGCN_package/SpaGCN/models.py#L52-L72

**Comment by jianhuupenn** [comment]
Please refer to:
#5
