### ISSUE TITLE
expression matrix for SpaGCN

### ISSUE THREAD

**Issue by archanabhardwaj** [jianhuupenn/SpaGCN#18]
Hi I am working on 10X visium data. I have data from four different tissue sections (2 replicates each). Each tissue section data was analyzed in spaceranger and got multiple output file such as tissue_positions_list.csv , tissue_image.tiff and filtered_feature_bc_matrix.h5 and many others. Now I would like to apply SpaGCN on my dataset to identify domains. As a input SpaGCN needs expression matrix, Spatial coordinates and image file. 
I have spatial coordinates (named as tissue_positions_list.csv) and image file  (named as  tissue_image.tiff ).  I am planning to use **filtered_feature_bc_matrix.h5 under** for the **expression_matrix.h5** option.  Please let me know if I am doing something wrong.

**Comment by jianhuupenn** [comment]
Hello, thanks for your interest in SpaGCN. Your proposed analysis sounds good to me. Just a few suggestions to check the correctness of the data:
1) Check if the coordinated in "tissue_positions_list.csv" can correctly map the spots onto the "tissue_image.tiff" image. You can refer to my answer in
https://github.com/jianhuupenn/SpaGCN/issues/7#issuecomment-962761985
2) For analyzing consecutive slides, you can refer to #14
