### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by bioinflix** [jianhuupenn/SpaGCN#19]
Hi, after installation I tried to run my data using SpaGCN following the tutorial. My data comes from 10X, and I used the filtered expression matrix, histology image, and tissue position files. The error below happened:

>>> s=1
>>> b=49
>>> adj=spg.calculate_adj_matrix(x=x_pixel,y=y_pixel, x_pixel=x_pixel, y_pixel=y_pixel, image=img, beta=b, alpha=s, histology=True)
Calculateing adj matrix using histology image...
..\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
..\anaconda3\lib\site-packages\numpy\core\_methods.py:180: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
Var of c0,c1,c2 =  nan nan nan
Var of x,y,z =  14381340.886740206 16155827.998378549 nan
>>> np.savetxt('D:/SpaGCN/adj.csv', adj, delimiter=',')
>>> adata=sc.read("D:/SpaGCN/sample_data.h5ad")
>>> adj=np.loadtxt('D:/SpaGCN/adj.csv', delimiter=',')
>>> adata.var_names_make_unique()
>>> spg.prefilter_genes(adata,min_cells=3)
>>> spg.prefilter_specialgenes(adata)
>>> sc.pp.normalize_per_cell(adata)
>>> sc.pp.log1p(adata)
>>> p=0.5
>>> l=spg.search_l(p, adj, start=0.01, end=1000, tol=0.01, max_run=100)
>>> n_clusters=7
>>> r_seed=t_seed=n_seed=100
>>> res=spg.search_res(adata, adj, l, n_clusters, start=0.7, step=0.1, tol=5e-3, lr=0.05, max_epochs=20, r_seed=r_seed, t_seed=t_seed, n_seed=n_seed)
Start at res =  0.7 step =  0.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..\anaconda3\lib\site-packages\SpaGCN\util.py", line 349, in search_res
    clf.train(adata,adj,init_spa=True,init="louvain",res=res, tol=tol, lr=lr, max_epochs=max_epochs)
  File "..\anaconda3\lib\site-packages\SpaGCN\SpaGCN.py", line 58, in train
    raise ValueError('l should not be set before fitting the model!')
ValueError: l should not be set before fitting the model!

Could you please help fix this problem? Thanks!

**Comment by jianhuupenn** [comment]
Please check if the XY coordinate correctly map the spots to the image. You can refer to #7.

**Comment by bioinflix** [comment]
> Please check if the XY coordinates correctly map the spots to the image. You can refer to #7.

Thanks! I have run it successfully on my data and got interesting results.  Another issue is about the plotting. How to draw the spatial domains and gene expression levels on the histology image?

**Comment by jianhuupenn** [comment]
I would recommend you to use ggplot2 in R to overlay the figures.
