### ISSUE TITLE
两组芯片合并后聚类问题（涉及批次效应）

### ISSUE THREAD

**Issue by xiazhk163** [jianhuupenn/SpaGCN#20]
你好
我看8. Multiple tissue sections analysis例子中两张芯片放在一起聚类，cluster有24个。理论上2张芯片上同一个功能区域应该被判断为同一个cluster，但可能涉及到批次效应等问题，实际情况并非如此，不知道您的工具是怎么处理这个情况的？
第二个问题：
如果我想只挑选某一个功能区域（即指定的cluster）在2个芯片组织上的差异表达基因，能不能直接借鉴6. Identify SVGs例子，会不会也受到批次效应的影响？
谢谢

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. I am not sure if I understand your question correctly, but our method does not have the batch effect correction function. If the 2 slides are from the same experiment, I think it will be able to identify shared common domains and unique domains as shown in the tutorial. I have not tried analyzing multiple slides from different studies jointly.

**Comment by xiazhk163** [comment]
Hi Jian
Thanks a lot for your reply. forgive me for my question in chinese. The 2 slides of my data are from the same experiment, but the shared common domains that I thought are not by SpaGCN (cluster 1 in slide A  is corresponding to cluster 3 in slide B). Maybe it is related to chip or sequencing.

**Comment by jianhuupenn** [comment]
Please refer to my response in #14, and feel free to let me know if this still does not answer your question.
