### ISSUE TITLE
cluster specific DEGs

### ISSUE THREAD

**Issue by archanabhardwaj** [jianhuupenn/SpaGCN#21]
I have used SpaGCN method for cluster analysis and identified spatial variable genes for each cluster. In my case, I am working on control and inflammed tissue section. After the clustering, I am interested in identifying differential genes based on the condition.  Is it possible to do it in SpaGCN ?

**Comment by jianhuupenn** [comment]
If you have 2 slides, say normal vs diseased, you can use SpaGCN to analyze them jointly to find the shared and unique domains. (#14 ) Then perform DE analysis between the same domain across different slides to find DEG for different conditions. Hope this helps!

**Comment by archanabhardwaj** [comment]
I am working on four slides i.e 2 normal and 2 diseased. This code works for 2 slides and got all the results. Next, I tried to run code for 4 slides, but it gives me error at  clf=spg.multiSpaGCN . It seems its not taking 4 slides data. 
Thanks in advance

**Comment by jianhuupenn** [comment]
SpaGCN should be able to take multiple slides as input. Can you show me the error message?
I haven't tested it using 4 slides. My concern is taking more slides will result in a high computation cost.
