### ISSUE TITLE
Contradictory gene in meta gene

### ISSUE THREAD

**Issue by ViriatoII** [jianhuupenn/SpaGCN#23]
Hey Jian,

I'm not sure if this is a bug or a feature:

What is the meaning of having a gene being considered both positive and negative for a metagene? Like this:

> ===========================================================================
Meta gene:  Camk2b+Celf4+Nell2-Celf4
===========================================================================

If the metagene function is a "log-linear combination of gene expression genes", does this mean that gene Celf4 cancels itself out? 

Cheers,
Ricardo

**Comment by jianhuupenn** [comment]
Yes. If this is the final output, the meta gene will just be:
Camk2b+Nell2.

**Comment by ViriatoII** [comment]
Great, thanks!
