### ISSUE TITLE
Spatial domain information in the starMap dataset (Figure 6a)

### ISSUE THREAD

**Issue by ciciQ777** [jianhuupenn/SpaGCN#24]
Hi spaGCN authors,

Thank you for developing such a wonderful tool. I would like to try it and also compare with other methods. I was wondering could you please tell me where I can get the domain information annotated for the starMap data you used in the figure 6a? I was trying to find it from the original paper but I failed to obtain it. Thank you very much!

**Comment by jianhuupenn** [comment]
Hi there. Thanks for your interest in SpaGCN. We assigned the identity of each spot based on the annotation from the original study.

**Comment by huBioinfo** [comment]
Dear Dr. Hu, 

Congrats to the excellent work! I'm wondering whether it is convenient for you to provide the seven-layer annotation of the STARmap dataset. I was not able to extract such information on the cell level from the original study. Thank you so much!

**Comment by jianhuupenn** [comment]
Please refer to:
https://github.com/jianhuupenn/SpaGCN/blob/master/results/Starmap_label.csv

**Comment by huBioinfo** [comment]
> Please refer to: https://github.com/jianhuupenn/SpaGCN/blob/master/results/Starmap_label.csv

Thank you so much for your reply! But it seems the "Starmap_label.csv" doesn't include your manually annotated (I suppose) anatomic structure information (i.e. HPC, cc, L6, L5, L4, L2/3 and L1 from left to right as shown in Fig.6a of the SpaGCN paper). Could you further provide this info? I really appreciate that!

**Comment by jianhuupenn** [comment]
https://github.com/jianhuupenn/SpaGCN/blob/master/results/Starmap_layer_label.csv

**Comment by huBioinfo** [comment]
> https://github.com/jianhuupenn/SpaGCN/blob/master/results/Starmap_layer_label.csv

Jian, thank you so mcuh for your generous sharing!
