### ISSUE TITLE
Error during Run SpaGCN

### ISSUE THREAD

**Issue by sokratiag** [jianhuupenn/SpaGCN#25]
Hi,

Thanks for the great tool! 

I am trying to run spaGCN on 10x Visium data but i get the following error during 'Run SpaGCN':

During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, target=None)" at /Users/user/.local/lib/python3.8/site-packages/umap_learn-0.4.6-py3.8.egg/umap/layouts.py (53)

Also, I have another issue. I load the visium histology image 'tissue_highres_image.png' using cv2.imread and the calculation of the adjacent matrix returns a nan array. I think the problem is with the image but this is a standard visium image so I am not sure what is going on. Any ideas?

Thanks!

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. Regarding your questions
1. Based on the current error message I cannot locate the error precisely. It seems to come from the UMAP visualization. my suggestion is to 1) check the dependency package versions, especially for scanpy. 2)Run SpaGCN line by line to better locate the error.
2. Please double-check the "x_pixel, y_pixel" correctly locate the spots on histology. You can refer to #7 for a similar issue.

**Comment by sokratiag** [comment]
Hi,

Thanks a lot for you help - I solved both issues as you suggested. 

The nan array is fixed when I load the .tif image instead of the .png (as suggested in https://github.com/jianhuupenn/SpaGCN/issues/7) 

The Run error also solved by updating umap-learn to the newest version (0.5.2). I think this error is related to any version older than 0.5+. Thanks!
