### ISSUE TITLE
No module named 'scipy.linalg.cython_lapack'

### ISSUE THREAD

**Issue by bioinflix** [jianhuupenn/SpaGCN#26]
Hi, When I import python modules, it occurred the following error after "import scanpy as sc":

~\anaconda3\lib\site-packages\scipy\linalg\__init__.py in <module>
    210 from ._solvers import *
    211 from ._procrustes import *
--> 212 from ._decomp_update import *
    213 from ._sketches import *
    214 from ._decomp_cossin import *

_decomp_update.pyx in init scipy.linalg._decomp_update()

ModuleNotFoundError: No module named 'scipy.linalg.cython_lapack'

The python version is 3.7.9, and the torch is successfully installed. I uninstalled SpaGCN and installed again, and following the environment settings suggestions according to the SpaGCN manual, but still could not solve the problem.

Could you help check what's the problem for this issue? Thanks!

**Comment by jianhuupenn** [comment]
Hi there,
Thanks for your interest in SpaGCN. It's my first time seeing this error info, and I recommend you to check the scanpy and scipy's version. It seems they are not compatible.

**Comment by bioinflix** [comment]
Thanks! The error disappeared after I updated scipy.
