### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JiayuanDing100** [jianhuupenn/SpaGCN#27]
https://github.com/jianhuupenn/SpaGCN/blob/7387c8e1c4e102e7aa6edc45b5e275f9c15665f1/SpaGCN_package/build/lib/SpaGCN/calculate_adj.py#L47

assert (x_pixel is not None) & (x_pixel is not None) & (image is not None)

should be assert (x_pixel is not None) & (y_pixel is not None) & (image is not None) ?

**Comment by jianhuupenn** [comment]
Thanks for reporting. I think this assertion will not affect the output of that function.
