### ISSUE TITLE
Question about SpaGCN on reported datasets

### ISSUE THREAD

**Issue by JiayuanDing100** [jianhuupenn/SpaGCN#28]
Hi,

Since I am new to spatial transcriptomics, I have a question about SpaGCN training on the Mouse Brain Sagittal Posterior dataset.

When I am looking at the Mouse Brain Sagittal Posterior dataset, it seems there is only one tissue image, please correct me if i am wrong. Then I am thinking you only have one training sample to train SpaGCN for clustering? I am not sure what my understanding is correct.

Thanks,
Jiayuan

**Comment by jianhuupenn** [comment]
SpaGCN is a fully unsupervised method and does not require a training process. It can be applied to a single tissue section.

**Comment by JiayuanDing100** [comment]
> SpaGCN is a fully unsupervised method and does not require a training process. It can be applied to a single tissue section.

I see. Thank you Jian!

So then if SpaGCN is a fully unsupervised method, could you point out what training datasets (no label involved) are you using?

**Comment by JiayuanDing100** [comment]
Oh, isee. You just directly apply SpaGCN on Mouse Brain Sagittal Posterior dataset to get clustering result, right?
