### ISSUE TITLE
Reproduction issue on tutorial

### ISSUE THREAD

**Issue by JiayuanDing100** [jianhuupenn/SpaGCN#29]
Hi Jian,

Initially, I wasn't able to reproduce the same or similar results with your reported ones in the tutorial.

Then I tried environment 3 you listed on the readme, but I still wasn't able to reproduce it and got similar results with the previous one.

The problem is that the results from the two environments i tried have huge differences with the reported results in the tutorial.

Best,
Jiayuan

**Comment by jianhuupenn** [comment]
Please refer to #3 
Even with a different environment, the results should be different but similar. I would suggest you check the adjacent matrix if looks the same as the one I uploaded in the toy data folder.

**Comment by xiao-kong-long** [comment]
hello, where the toy data folder?

**Comment by jianhuupenn** [comment]
https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/download_data.md
