### ISSUE TITLE
performance is not as good as shown in the tutorial?

### ISSUE THREAD

**Issue by 21century-bio** [jianhuupenn/SpaGCN#3]
Hi, thanks a lot for the nice work and code! 

When I run the `tutorial.ipynb`, the spatial domain identification results are like:

![图片](https://user-images.githubusercontent.com/88523541/128453062-1cff432e-2dd8-408e-acc6-3c580b8bc2fc.png)
![图片](https://user-images.githubusercontent.com/88523541/128453076-af6cca26-c2d7-47ae-b89c-82b94cb3805d.png)

while the figures you provide (`pred.png` and `refined_pred.png`) have much clearer clustering results than I got.
![图片](https://user-images.githubusercontent.com/88523541/128453318-9a57a957-e8b8-42da-9c06-38df49a8ffb2.png)
![图片](https://user-images.githubusercontent.com/88523541/128453366-c9bf2f4b-3d97-4058-a20a-6166804d7793.png)

I didn't change any code in the notebook, I wonder why the results look quite different? Is there anything else needs to be processed?

Thanks!

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN.
SapGCN utilizes Louvain to initialize the clusters and most of the variability comes from this step. To get exactly the same results as the tutorial, you need to set the same environment, especially the package versions and seed. All the results in the tutorial and results reported in the paper are obtained using Environment 1 (https://github.com/jianhuupenn/SpaGCN#versions-the-software-has-been-tested-on) with the random seed, numpy seed and torch seed all setting to 100.

**Comment by 21century-bio** [comment]
Thanks! I'll try.

**Comment by mbabadi** [comment]
I have the same issue here -- tutorial does not reproduce. @21century-bio did you manage to reproduce the results?
