### ISSUE TITLE
the mouse visual cortex STARmap data

### ISSUE THREAD

**Issue by zzdj11** [jianhuupenn/SpaGCN#30]
Hello, I am new to spatial transcriptomics. I am now trying to reproduce spaGCN, but for the original expression matrix of the mouse visual cortex STARmap data I found that the number of cells is inconsistent and I need to filter it, but I always can't get the correct filtered expression matrix, can you please provide the expression matrix of the STARmap data for the experiment? Thank you!

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. The section we used is 20180505_BY3.

**Comment by zzdj11** [comment]
The problem has been solved.
Thank you very much for the clarification!
