### ISSUE TITLE
A bug report

### ISSUE THREAD

**Issue by tonyyang1995** [jianhuupenn/SpaGCN#32]
Hi there, thanks for sharing your work. When I ran the tutorial, when you are generating the adj matrix with image information, are you making it on purpose to use:
`adj=spg.calculate_adj_matrix(x=x_pixel,y=y_pixel, x_pixel=x_pixel, y_pixel=y_pixel, image=img, beta=b, alpha=s, histology=True)
`
or it should be a typo and it should be:
`adj=spg.calculate_adj_matrix(x=x_array,y=y_array, x_pixel=x_pixel, y_pixel=y_pixel, image=img, beta=b, alpha=s, histology=True)
`
Otherwise I generated with a wrong adj matrix when comparing with the adj_matrix from your google drive.

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN.
This is not a typo. The adjacent matrix from array/pixel coordinates will be different, but the neighbourhood info will be the same and will generate the same spatial domains. 
I put 
```
adj=spg.calculate_adj_matrix(x=x_pixel,y=y_pixel, x_pixel=x_pixel, y_pixel=y_pixel, image=img, beta=b, alpha=s, histology=True)
```
in the tutorial because some datasets only have pixel coordinates.
