### ISSUE TITLE
Tutorial for imaging-based spatial data

### ISSUE THREAD

**Issue by zhanglab2008** [jianhuupenn/SpaGCN#35]
Hi team,
great work! do you have a tutorial to analyze the imaging-based spatial data? such as Merfish, etc? For example, those techniques don't include a histology image, how can I calculate the adjacency matrix? Thanks in advance?

**Comment by jianhuupenn** [comment]
Thanks for your interest in our method. 
SpaGCN can be directly used on MERFISH data, as we showed in our original paper. In the tutorial Section 4[https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md#4-integrate-gene-expression-and-histology-into-a-graph]:
```
#If histlogy image is not available, SpaGCN can calculate the adjacent matrix using the fnction below
#adj=calculate_adj_matrix(x=x_pixel,y=y_pixel, histology=False)
```

**Comment by zhanglab2008** [comment]
great, thanks! I will give it a try!

**Comment by zhanglab2008** [comment]
I tried and it worked! Thank you! Very interestingly, when applying SpaGCN to Merfish data, the results are not just spatial regions but very high-resolution cell clustering, much better than the clustering results from the popular clustering tools such as Scanpy and Seurat! So impressive!
