### ISSUE TITLE
calculation procedure exceeds maximum memory resource

### ISSUE THREAD

**Issue by lifan18** [jianhuupenn/SpaGCN#36]
Dear Dr. Hu,

SpaGCN is a very helpful software! Thank you very much for your work!

I was trying to run this programme for my samples, however, the calculation procedure of one sample required a very large memory resource which was beyond our HPC limitation. I was wondering if there has checkpoint in SpaGCN which can enable the programme to continue calculating. May you have other advice for this issue? 

Thank you!

Regards,

Li Fan

```
Traceback (most recent call last):
  File "spaGCN.py", line 30, in <module>
    adj = distance.cdist(X, X, 'euclidean') #adjmatrix
  File "/usr/nzx-cluster/apps/SpaGCN/1.2.5/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2954, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
numpy.core._exceptions.MemoryError: Unable to allocate 1.64 TiB for an array with shape (475181, 475181) and data type float64
```

**Comment by jianhuupenn** [comment]
Thanks for your interest in our method. It seems your data contains >400k spots, and the adjacent matrix(475181 by 475181) is consuming a lot of RAM.
Unfortunately, calculating the adjacent matrix is the very first step and I do not have a clear solution to the RAM issue given such a large sample size. 
I guess the data you are analyzing is sub-cellule  level? So one possible solution is to merge the spots using a grid to reduce the sample size.
