### ISSUE TITLE
batch effect from ST data generated by multiple sequencing chips

### ISSUE THREAD

**Issue by lifan18** [jianhuupenn/SpaGCN#37]
Dear Dr. Hu,

I ran my data with SpaGCN and found this software is good for Spatial transcriptomic data generated by one chip. On the other hand, the results from the ST data combined from multiple sequencing chips show batch effect.

Please see the figure below.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/44634495/179996102-ed2d7ad6-6ee6-4f8a-b0bc-5fbb1f5b5efd.png">

The same cluster from different chips cannot be grouped together based on this result.

I tried to use SCTransform(https://satijalab.org/seurat/articles/sctransform_vignette.html) to correct batch effect, but the transformed data cannot be used in SpaGCN as I ran before.

Meanwhile, I saw SpaGCN also has the procedure of normalization.

```
#Normalize and take log for UMI
sc.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)
```

May you have any advice about batch correction for running SpaGCN?

Thank you very much!

Li Fan

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. We find that z-score normalization can greatly improve the multi-section analysis.

**Comment by lifan18** [comment]
Appreciate! Thanks for your finding and informing me this!

Best!
