### ISSUE TITLE
A question about SpaGCN' data

### ISSUE THREAD

**Issue by zhaofangyuan98** [jianhuupenn/SpaGCN#38]
Dear Dr. Hu,

       Thank you for making SpaGCN available. 

       When I trying reproducing your SpaGCN, I have some problems about data. Could you give me your ST h5ad data and STARmap h5ad data used in your paper. 

       Thank you!

Best wishes,

Zhao Fangyuan

**Comment by jianhuupenn** [comment]
The data are too big to be directly uploaded to Github. Please find the links for downloading in the supplement.
