### ISSUE TITLE
Student's t bug report

### ISSUE THREAD

**Issue by tomo61098** [jianhuupenn/SpaGCN#41]
https://github.com/jianhuupenn/SpaGCN/blob/0f265b80ff7525d68be07d6989283f3e9e575bf6/SpaGCN_package/SpaGCN/models.py#L26
Hello Dr. Hu,

should the expression be `q = q**((self.alpha+1)/2.)` or is it intended to first raise to the power and then take half of the result?

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. The formula is correct.
