### ISSUE TITLE
How could I get the ground truth of GSE111672?

### ISSUE THREAD

**Issue by amssljc** [jianhuupenn/SpaGCN#42]
Thanks for your work! How could I get the ground truth of GSE111672? It is a Primary pancreatic cancer tissue dataset, but I can only get the expression matrix. Also, I am a fresh in ST area. Could you tell me how to assign coordinates such as '10x30' in the expression matrix to the spatial image which has 30000x40000 pixels?

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. The annotation is from the figures in the original publication.
In this case, you need to do the manual mapping on your own to transform the array coordinates into pixel coordinates. I didn't find any existing package that can help you with this.
