### ISSUE TITLE
Error at the steps with louvain algorithm

### ISSUE THREAD

**Issue by avsarg** [jianhuupenn/SpaGCN#43]
Hi! First of all, thanks for this nice method, SpaGCN. I want to run it for my own data and follow the given tutorial (https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.ipynb). However, I got error which says “**BaseException: Could not construct partition: vector too long**” at the steps which use Louvain algorithm.

Can you please help me to solve this problem?

Thanks,

**Comment by avsarg** [comment]
It is solved, thanks.

**Comment by huimin230** [comment]
> It is solved, thanks.

Hi, I have the similar problem, "BaseException: Could not construct partition: vector", could you please let me know how did you solve this problem?

Big thanks!

**Comment by avsarg** [comment]
Hi, in my situation, the problem occurred bcz of version mismatch between anndata, scipy, h5py, louvain and so. I just created a new environment which is similar to the tested "Enviroment 3" in Readme file, and the problem solved.
