### ISSUE TITLE
when histlogy image is not available, SpaGCN calculating the adjacent matrix showed "segmentation fault""

### ISSUE THREAD

**Issue by 20182531027** [jianhuupenn/SpaGCN#46]
Thanks for your splendid software, and I came across some issues when following the tutorial.
![image](https://user-images.githubusercontent.com/92516659/194735772-81c59db1-0350-4f49-852b-877bedb892fb.png)
i don't know why that happened, could you give me some instrustions? thank you

**Comment by jianhuupenn** [comment]
It's the first time I saw this error message. Let's first figure out if it results from the environment.
If you calculate the adjacent matrix without a histology image using the sample data I provided, will you get the same error?
