### ISSUE TITLE
Error running spaGCN : Could not construct partition

### ISSUE THREAD

**Issue by archanabhardwaj** [jianhuupenn/SpaGCN#47]
Hello 
 I am trying to run spatial 10X visium data in sgaGCN on spatial dataset but it gives me following error at processing step : 
#Search for suitable resolution
res=spg.search_res(adata, adj, l, n_clusters, start=0.7, step=0.1, tol=5e-3, lr=0.05, max_epochs=20, r_seed=r_seed, t_seed=t_seed, n_seed=n_seed)
****BaseException: Could not construct partition: vector::_M_default_append****

Same code was working before on single and integrated datasets. 
But this time it gives me error for both integrated and single objects.

Please help me to fix this issue. I would appreciate all the suggestions.
Thanks in advance

**Comment by xiao-kong-long** [comment]
I also meet this problem now.

**Comment by xiao-kong-long** [comment]
hello, you can try the solution closed issue #43
