### ISSUE TITLE
About the rank_genes_groups function in utils.py

### ISSUE THREAD

**Issue by LindsayMo** [jianhuupenn/SpaGCN#52]
Dear Dr. Hu!

After reading the SpaGCN tutorial, step 6. Identify SVGs. I have a question of the codes in funciton rank_genes_groups in utils.py

```
pvals_adj=[i[0] for i in adata.uns['rank_genes_groups']["pvals_adj"]]
genes=[i[1] for i in adata.uns['rank_genes_groups']["names"]]
```

I think, to ensure the data correspondence, the indexes in line 1 and line 2 should be the same, such as
```
pvals_adj=[i[0] for i in adata.uns['rank_genes_groups']["pvals_adj"]]
genes=[i[0] for i in adata.uns['rank_genes_groups']["names"]]
```
or
```
pvals_adj=[i[1] for i in adata.uns['rank_genes_groups']["pvals_adj"]]
genes=[i[1] for i in adata.uns['rank_genes_groups']["names"]]
```

I wish to know the reason to choose the different indexes.

Thanks!

Mo

**Comment by jianhuupenn** [comment]
The test is two-sided, so the p-values should have the same significant level.
