### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by yuchen345** [jianhuupenn/SpaGCN#53]
Hi,

Very cool tool ! I'm working with SpaGCN with my own data and encountering the same error as #33 .

 I looked back to my data and found adata.shape[0] was indeed not equal to adj.shape[0] and adj.shape[1].

Anything wrong happened with my data procecing ? Hoping for your reply!

Thanks a lot

**Comment by Sun-Yazhou** [comment]
Hi, 
I think it probably because you used spg.prefilter_cells(). You can try to recalculate adj after filtering.
