### ISSUE TITLE
spatial location file

### ISSUE THREAD

**Issue by YyLu5** [jianhuupenn/SpaGCN#58]
Hello, 

Thank you so much for this useful tool for domain detection. I'm trying to use it on my own data, but I only have pixel coordinates. I followed your tutorial with your example data, everything works fine. I'm wondering if I don't have x_array/y_array, how can I proceed? Especially x/y_array are needed in spg.calculate_adj_matrix function. 

Or if I only have x/y array, can I replace the x/y pixel in the tutorial with them? 

Thank you.

**Comment by zji90** [comment]
I have the same question. Data other than Visium (e.g., MERFISH) does not have x/y array. Only x/y coordinates are available.

**Comment by jianhuupenn** [comment]
Please use the same x/y coordinates as x/y array.
