### ISSUE TITLE
Example data not available 

### ISSUE THREAD

**Issue by vladimirkovacevic** [jianhuupenn/SpaGCN#62]
In the tutorial, the data used in the analysis is not available in the repo. Could you maybe add a link to the file? 
```
adata = read_10x_h5("../tutorial/data/151673/expression_matrix.h5")
spatial=pd.read_csv("../tutorial/data/151673/positions.txt",sep=",",header=None,na_filter=False,index_col=0) 
```

**Comment by jianhuupenn** [comment]
https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/download_data.md

**Comment by vladimirkovacevic** [comment]
Maybe you could add:
"Data can be downloaded at: https://drive.google.com/drive/folders/1zten54vkjorp26T4iD0ApQGa9ut5eY42?usp=sharing"
To tutorial notebooks.
