### ISSUE TITLE
search_l gives None

### ISSUE THREAD

**Issue by cnk113** [jianhuupenn/SpaGCN#7]
Hello,

I'm running the main tutorial but when I run `search_l` it returns None.
And then when running `search_res` I get: `l should not be set before fitting the model!`
I'm running the default values in the tutorial. Any ideas to get around this?

Thanks,
Chang

**Comment by jianhuupenn** [comment]
Hi Chang,

Are you using the toy data or your own data?
If the search_l() function give None, that means the search range and search step is not suitable. It should also out a message to help you on how the change these parameters. Could you show me the message? Something like:

```
"Exact l not found, closest values are: l=xxx, p=xxx"
```

Jian

**Comment by cnk113** [comment]
Sorry for the late followup it is my own dataset.
I don't seem to be getting the message from search_l, is there more verbose parameter?

**Comment by cnk113** [comment]
Also rerunning the tutorial I also get some nans
```
adj=spg.calculate_adj_matrix(x=x_pixel,y=y_pixel, x_pixel=x_pixel, y_pixel=y_pixel, image=img, beta=b, alpha=s, histology=True)

Calculateing adj matrix using histology image...
Var of c0,c1,c2 =  nan nan nan
Var of x,y,z =  2720369.009340232 5921502.8994199475 nan
```

**Comment by jianhuupenn** [comment]
Hi Chang,
I figured out the cause of the error. The message
```
Var of c0,c1,c2 =  nan nan nan
```
indicates SpaGCN is not able to get the color value from the image using the coordinate "x_pixel, y_pixel". Please double-check the "x_pixel, y_pixel" correctly locate the spots on histology. 
You can visualize the coordinates on histology using:
```
res=10
img_new=img.copy()
for i in range(len(x_pixel)):
	x=x_pixeli]
	y=y_pixel[i]
	img_new[int(x-res):int(x+res), int(y-res):int(y+res),:]=255

cv2.imwrite('./test_mapping.jpg', img_new)
```
The codes above mark the pixel xy spots on the histology with white dots. "res" controls the size of the dot. You can check if these dots locate correctly.
Let me know if you have further questions.
Jian

**Comment by cnk113** [comment]
Hey Jian,

It looks like there are no white dots in my mapped images with code snippet above. Do you know why it's not imprinting?

Best,
Chang

**Comment by cnk113** [comment]
[test.tar.gz](https://github.com/jianhuupenn/SpaGCN/files/7493945/test.tar.gz)
I've uploaded the filtered h5, coordinates, and the histology here if it help.

**Comment by jianhuupenn** [comment]
You can increase "res" to 100. If still no dots, that means the coordinates are not matching the histology.
Could you also check the range of x_pixel, y_pixel and the size of the histology image?

**Comment by jianhuupenn** [comment]
I have looked into your data, it seems
The "x_pixel" ranges from 1125 to 11422, 
the "y_pixel" ranges from 938 to 11730, 
while your image is only 1995x2000.

I think the coordinates do not match the image. They may match a higher-resolution histology image.

**Comment by cnk113** [comment]
Ah I see, I'll try to use the raw tif rather than jpg.

**Comment by suke18** [comment]
Jian, I run into the same issue. It seems that I can read into the jpg file but the search_l function does not recognize the existence of this. The image parameter is still none.

**Comment by jianhuupenn** [comment]
I think the error in the original issue is because the coordinates do not match the histology image. So I highly recommend you check the concordance between the coordinates and the image. The image is usually read in as a 3D numpy array. You may also check if it is loaded correctly.

**Comment by suke18** [comment]
Okay, I see. It is weird to see some pixel coordinates are beyond the weights and heights of the images. So the variance of the z calculation will be nan. Thanks for your reply.
