### ISSUE TITLE
About the extended application of SpaGCN

### ISSUE THREAD

**Issue by makabakayu** [jianhuupenn/SpaGCN#75]
Hi Dr. Hu!

I wondered if I could apply this method to non-gene expression matrix, where my input is a low-dimensional matrix with columns representing spots while rows representing the proportions of each cell type, and there is only 30 rows so I don't need to perform preprocessing and PCA. Is there any way for the graph convolutional network to take my matrix directly as input without any processing?

Thanks!

**Comment by jianhuupenn** [comment]
Theatrically, it should work. You will need to modify the main function in  [SpaGCN.py](https://github.com/jianhuupenn/SpaGCN/blob/master/SpaGCN_package/SpaGCN/SpaGCN.py)
to disable PCA.
