### ISSUE TITLE
Can't reproduce my results

### ISSUE THREAD

**Issue by yunbokai** [jianhuupenn/SpaGCN#77]
Hi, 
    I use the easy mode to my data with code below:
```
#Set seed
r_seed=t_seed=n_seed=100
#Search for suitable resolution
#Set seed
random.seed(r_seed)
torch.manual_seed(t_seed)
np.random.seed(n_seed)
#Run SpaGCN
adata.obs["pred"]= spg.detect_spatial_domains_ez_mode(adata, img, x_array, y_array, x_pixel, y_pixel, n_clusters=7, histology=True, s=1, b=49, p=0.5, r_seed=100, t_seed=100, n_seed=100)
adata.obs["pred"]=adata.obs["pred"].astype('category')
#Refine domains (optional)
#shape="hexagon" for Visium data, "square" for ST data.
adata.obs["refined_pred"]=spg.spatial_domains_refinement_ez_mode(sample_id=adata.obs.index.tolist(), pred=adata.obs["pred"].tolist(), x_array=x_array, y_array=y_array, shape="hexagon")
adata.obs["refined_pred"]=adata.obs["refined_pred"].astype('category')
```
   However, each time I ran the same code, I got a similar but different domain result. I want to make the result reproducible. Do you have some advice? 

Best wishes,
18k

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. 
I have tested our method on 3 OS with Intel chips (https://github.com/jianhuupenn/SpaGCN#versions-the-software-has-been-tested-on), and setting the same seed will generate exactly the same results. I suspect that your issue results from the hardware. Are you using a machine with M1/2 chip?

**Comment by WJPina** [comment]
I got the same issue, did you find the solution?
