### ISSUE TITLE
`IndexError` in `spg.find_meta_gene`

### ISSUE THREAD

**Issue by Nick-Eagles** [jianhuupenn/SpaGCN#8]
Hello,

I'm following along [the tutorial](https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.md) but using my own `AnnData` and histology image. When calling `spg.find_meta_gene` [as in the tutorial](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/tutorial/tutorial.md#7-identify-meta-gene), I get the following error:

```
Trying to set attribute `.obs` of view, copying.
WARNING: It seems you use rank_genes_groups on the raw count data. Please logarithmize your data before calling rank_genes_groups.
Add gene:  ENSG00000197971
Minus gene:  ENSG00000111341
Absolute mean change: 4.6624002
Number of non-target spots reduced to: 77
===========================================================================
Meta gene is:  ENSG00000131095+ENSG00000197971-ENSG00000111341
===========================================================================
Trying to set attribute `.obs` of view, copying.
WARNING: It seems you use rank_genes_groups on the raw count data. Please logarithmize your data before calling rank_genes_groups.
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/jhpce/shared/jhpce/libd/spagcn/1.2.0/spagcn_venv/lib/python3.7/site-packages/SpaGCN/util.py", line 304, in find_meta_gene
    add_g=tmp.uns['rank_genes_groups']["names"][0][1]
  File "/jhpce/shared/jhpce/libd/spagcn/1.2.0/spagcn_venv/lib/python3.7/site-packages/numpy/core/records.py", line 292, in __getitem__
    obj = nt.void.__getitem__(self, indx)
IndexError: invalid index (1)
```

To be more precise, I ran the following for my `AnnData`:

```
#  Read in raw data and subset to current sample (my AnnData has several samples)
raw = sc.read_h5ad(input_adata_path)
raw.var_names_make_unique()
raw = raw[raw.obs.sample_id == sample_name, :]

# adata.obs["pred"] was computed earlier using code provided in your tutorial
raw.obs["pred"] = adata.obs["pred"].astype('category')

# Set names to match tutorial, given names present in my AnnData
raw.obs["x_array"]=raw.obs["array_row"]
raw.obs["y_array"]=raw.obs["array_col"]
raw.obs["x_pixel"]= raw.obs["pxl_col_in_fullres"]
raw.obs["y_pixel"]= raw.obs["pxl_row_in_fullres"]

#Convert sparse matrix to non-sparse
raw.X=(raw.X.A if issparse(raw.X) else raw.X)
raw.raw=raw
sc.pp.log1p(raw)

# In my case 8 spatial domains were found, and my AnnData contains gene IDs
# as Ensembl IDs rather than gene symbols. The start gene is still GFAP, and I've verified
# the gene is present in my AnnData
meta_name, meta_exp=spg.find_meta_gene(input_adata=raw,
                    pred=raw.obs["pred"].tolist(),
                    target_domain=7,
                    start_gene="ENSG00000131095",
                    mean_diff=0,
                    early_stop=True,
                    max_iter=3,
                    use_raw=False)
```

As the error message suggests, [this line](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L304) triggers the error. I manually ran code from `spg.find_meta_gene` line-by-line, discovering that the error occurred on i=1 [here](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L297), and the value of `tmp.uns['rank_genes_groups']["names"][0]` is `('ENSG00000268674',)`, which of course has no `[1]` index, leading to the `IndexError` I see.

I apologize for not providing a small directly reproducible example, as I couldn't produce the error with your example data, and I didn't think it was practical to share my large `AnnData` file directly. Please let me know how I could provide more useful information.

Thanks in advance for any help.

Best,

-Nick

**Comment by jianhuupenn** [comment]
Hi Nick,

This is the first time I saw this error and I cannot provide a clear answer to it. The error comes from spg.find_meta_gene():
```
sc.tl.rank_genes_groups(tmp, groupby="target",reference="rest", n_genes=1,method='wilcoxon')
adj_g=tmp.uns['rank_genes_groups']["names"][0][0]
add_g=tmp.uns['rank_genes_groups']["names"][0][1]
```
In this step, SpaGCN uses sc.tl.rank_genes_groups() function from scanpy to do the differential expression analysis. When the "n_genes=1", there should be 2 genes stored in:
```
tmp.uns['rank_genes_groups']["names"][0]
```
The first gene is the DE gene for "rest" group and the second gene is for "target" group. 
Since your output is 
```
('ENSG00000268674',) #This comma here maybe the clue.
```
I guess it indicates
1) The gene name has some error or
2) No DE gene can be found for the "target" group.
My suggestion is to:
1) Check if the current meta gene "ENSG00000131095+ENSG00000197971-ENSG00000111341" already has a clear pattern.
2) Check the 
```
tmo.obs["target"].value_counts()
```
to confirm that the number of spots in each group is not 0.
3) Check scanpy version. The version I am using is '1.5.1' and it works well for all the 7 datasets I analyzed.

Best,
Jian

**Comment by Nick-Eagles** [comment]
Thanks for your detailed feedback. I do see that just after [this line](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L300) to compute `tmp` on the second iteration of [this for loop](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L297), that there are only target spots:

```
>>> tmp.obs.target.value_counts()
1    143
Name: target, dtype: int64
```

If I understand correctly, this is a bug affecting the (probably uncommon) case where there are exactly 0 non-target cells selected in [these lines](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L299-L300), since [the following line](https://github.com/jianhuupenn/SpaGCN/blob/50c3fb964ee5070273cc77b8654242c6538e1ce7/SpaGCN_package/SpaGCN/util.py#L302) assumes there are cells in both groups, as you pointed out. I imagine you'd want to return from the function in this case rather than proceed, though I'm not totally sure I understand the algorithm.

Thanks again.

**Comment by jianhuupenn** [comment]
Yes., that makes sense. You can use the previous round results as the meta gene, that is, "ENSG00000131095+ENSG00000197971-ENSG00000111341".
I'll modify the function to make it stop when the non-target set is empty.

Thanks!

**Comment by jianhuupenn** [comment]
I have updated the spg.find_meta_gene() funtion on GitHub, now it should not have this error. Thanks for your bug report! Really appreciated.

**Comment by Nick-Eagles** [comment]
No problem, thanks for the responsiveness and quick fix. Unfortunately I get this error with the new code:

```
Traceback (most recent call last):
  File "01_run_spagcn.py", line 256, in <module>
    use_raw=False)
  File "/jhpce/shared/jhpce/libd/spagcn/1.2.0/spagcn_venv/lib/python3.7/site-packages/SpaGCN/util.py", line 301, in find_meta_gene
    if len(set(tmp.obs["target"])<2):
TypeError: '<' not supported between instances of 'set' and 'int'
```

I believe the parenthesis are misplaced: specifically that `len(set(tmp.obs["target"])<2)` should instead be `len(set(tmp.obs["target"]))<2`. This is obviously easy for me to fix on my end, but I wanted to let you know for other users.

Thanks!

**Comment by jianhuupenn** [comment]
Fixed, thank you!
