### ISSUE TITLE
module 'SpaGCN' has no attribute 'calculate_adj_matrix'

### ISSUE THREAD

**Issue by JavadP4** [jianhuupenn/SpaGCN#82]
Hi!
I'm trying to reproduce the tutorial's example. 
But got this error when tried to call this function "SpaGCN.calculate_adj_matrix()"
It seems that function name was changed.

**Comment by rocketeer1998** [comment]
You should write `spg.calculate_adj_matrix(x = x_pixel,y = y_pixel, histology=False)`.
