### ISSUE TITLE
`TypeError` in `spg.find_meta_gene`

### ISSUE THREAD

**Issue by Nick-Eagles** [jianhuupenn/SpaGCN#9]
Hello,

Sorry to bother you with another issue. After executing the same code as in #8 with the same input data (but a different number of clusters), I got a seemingly unrelated error (at the same line of code containing `spg.find_meta_gene`):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jhpce/shared/jhpce/libd/spagcn/1.2.0/spagcn_venv/lib/python3.7/site-packages/scanpy/tools/_rank_genes_groups.py", line 590, in rank_genes_groups
    test_obj = _RankGenes(adata, groups_order, groupby, reference, use_raw, layer, pts)
  File "/jhpce/shared/jhpce/libd/spagcn/1.2.0/spagcn_venv/lib/python3.7/site-packages/scanpy/tools/_rank_genes_groups.py", line 110, in __init__
    "contain one sample.".format(', '.join(invalid_groups_selected))
TypeError: sequence item 0: expected str instance, int found
```

I checked `tmp.obs["target"].value_counts()`, as we discussed in #8, in case something similar was going on:

```
>>> tmp.obs["target"].value_counts()
1    136
0      1
```

I'm wondering if it's a problem that only 1 non-target cell exists. Thanks for your help with the issues so far.

Best,

-Nick

**Comment by jianhuupenn** [comment]
I am not sure if the error happened because the non-target group only have 1 cell, but I do think it is necessary to set a cutoff, say 5 cells. If the number of cells in any group is less than this cut-off, then stop. Thanks for reporting, I'll update it then.

**Comment by Nick-Eagles** [comment]
Thanks for the feedback and code update. Originally I encountered the error in 2 different scenarios, but after your update, the code ran without any issues, so I think whatever the issue was is gone. Thanks again.
